name: safe_session_storage
version: 0.0.1

environment:
  sdk: ">=2.18.0-261.0.dev <3.0.0"

dependencies:
  path: ^1.8.2
  uuid: ^3.0.6
  synchronized: ^3.0.0+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  collection: ^1.16.0
